### ISSUE TITLE
Cannot find type 'uint8' in scope and type of expression is ambiguous

### ISSUE THREAD

**Issue by chmac** [lynixliu/SwiftAvroCore#23]
Firstly, thanks for this library. It's been a huge help to us that we can use Avro in Swift. Much appreciated.

After I imported the library into my React Native .xcworkspace, when I try to build, I find the following errors:

```
SourcePackages/checkouts/SwiftAvroCore/Sources/SwiftAvroCore/IPC/Response.swift:13:25 Cannot find type 'uint8' in scope
SourcePackages/checkouts/SwiftAvroCore/Sources/SwiftAvroCore/IPC/Response.swift:16:47 Cannot find type 'uint8' in scope
SourcePackages/checkouts/SwiftAvroCore/Sources/SwiftAvroCore/IPC/Response.swift:20:31 Cannot find 'uint8' in scope
SourcePackages/checkouts/SwiftAvroCore/Sources/SwiftAvroCore/IPC/Response.swift:27:66 Cannot find type 'uint8' in scope
SourcePackages/checkouts/SwiftAvroCore/Sources/SwiftAvroCore/IPC/Response.swift:47:32 Type of expression is ambiguous without more context
SourcePackages/checkouts/SwiftAvroCore/Sources/SwiftAvroCore/IPC/Response.swift:85:45 Type of expression is ambiguous without more context
SourcePackages/checkouts/SwiftAvroCore/Sources/SwiftAvroCore/IPC/Response.swift:104:45 Type of expression is ambiguous without more context
SourcePackages/checkouts/SwiftAvroCore/Sources/SwiftAvroCore/IPC/Response.swift:109:49 Type of expression is ambiguous without more context
SourcePackages/checkouts/SwiftAvroCore/Sources/SwiftAvroCore/IPC/Response.swift:136:49 Type of expression is ambiguous without more context
```

I'm super new to Swift, this is the first real project that I'm working on, so I'm a bit lost. I thought the type was `UInt8` rather than `uint8`, but I don't know if Swift is case sensitive, etc.

Do you have any idea how I could fix this issue? Maybe I have imported the library incorrectly or missed some instructions in the setup?

**Comment by chmac** [comment]
It looks like I found a workaround by forking the repo and deleting the IPC folder. If anyone else finds this issue with the same problem, I did that by adding this URL as my dependency `https://github.com/chmac/SwiftAvroCore/` with the branch set to `remove-ipc`.

**Comment by lynixliu** [comment]
Just as @chamc saids, it should be UInt8 in IPC/Response.swift. As this project is full of UInt, UInt32, UInt64 etc.
