### ISSUE TITLE
'NullCodec' initializer is inaccessible due to 'internal' protection level

### ISSUE THREAD

**Issue by chmac** [lynixliu/SwiftAvroCore#24]
I think this is caused by the lack of a `public` keyword here:

https://github.com/lynixliu/SwiftAvroCore/blob/640aaa5e968c4dab4bea070646efa8d8fef4bd82/Sources/SwiftAvroCore/FileObject/NullCodec.swift#L62-L64

**Comment by lynixliu** [comment]
Yes, the NullCodec is not opened to public yet. Merged from [chmac:null-codec-init-public](https://github.com/chmac/SwiftAvroCore/tree/null-codec-init-public)
