### ISSUE TITLE
Unable to decode nested records

### ISSUE THREAD

**Issue by chmac** [lynixliu/SwiftAvroCore#28]
We were getting an error trying to decode a nested record:

Fatal error: Unexpectedly found nil while unwrapping an Optional value

Here:

https://github.com/chmac/SwiftAvroCore/blob/640aaa5e968c4dab4bea070646efa8d8fef4bd82/Sources/SwiftAvroCore/Codable/AvroDecodable.swift#L246

Since the error, we've decided to abandon Avro in Swift, so I gave up trying to figure out how to fix this error. I believe that the `schemaMap` inside the nested record is invalid. In my tests, the key for my nested field was `string` instead of `foo`. By that, I mean the key inside the `schemaMap` defined [AvroDecodable.swift line L243](https://github.com/lynixliu/SwiftAvroCore/blob/ffa48bd103ff4c8966f20c7336f350974733e447/Sources/SwiftAvroCore/Codable/AvroDecodable.swift#L243). I didn't get far enough to figure out why this was the case. In all other cases that I could see, the key was set correctly. But it seems like something goes awry with nested record types.

**Comment by lynixliu** [comment]
I'd a pity to hear that this error blocked your efforts. The nest record is a little tricky to implement as the inner types are dynamic and the reflection function in Swift is very limited, but it seems this error is much more related to the implementation.  Could you please share a test case or the nested record of the problem, I will try to fix this issue in the next update.

**Comment by chmac** [comment]
I think an example like this fails:

```json
{
    "name": "Rec",
    "type": "record",
    "fields": [
        {
            "name": "fel",
            "type": {
                "name": "Fel",
                "type": "record",
                "fields": [
                    {
                        "name": "bea",
                        "type": "string"
                    }
                ]
            }
        }
    ]
}
```

But I can't be 100% sure as we took out the avro piece from our Swift code already.

**Comment by chmac** [comment]
Maybe there's some inspiration in how the swift core JSON encoder / decoder handles this?

I tried to wrap my head around the Avro decoder, but I couldn't figure it out. I'm pretty new to Swift so I had a hard time with some of the syntax which I haven't seen before.

**Comment by lynixliu** [comment]
@chmac , thank you for sharing the record json. Pull request #29 can decode the nested record. The root cause relate to optional field in record. Please check out the develop branch to get the update.
Currently, the name reference is very limited, only support same level ahead reference, for example, one item in fields can use the name of previous field, but not support the inner level of the previous field.

**Comment by chmac** [comment]
Is there an optional type in my example above? I thought optionals in avro were a union of `null` and another type. But hey, if the schema works, that's a great help. Thanks for looking into this so quickly.

We gave up on avro in Swift for some of our data transfer, but now I see that to load binary files into react native they have to be encoded into base64 and sent over the JavaScript bridge, so we might end up having to do some decryption work in Swift, in which case we'll need the fixes you just created. Thanks in advance if we do! :-)

**Comment by lynixliu** [comment]
After carefully checking your issue, It seems it is not resolved yet, the previous update only relate to schema decode, not the  Avro binary bytes decode to swift structure. Currently, this project support decode Avro binary bytes to dynamic type like array of dictionary and to swift structures.  Could you please share me your expected swift type of the "Rec" record to be decoded.  According to the AVRO spec, the encoded of record only include the fields, that is the binary stream would only contains the string of name "bea", something like string "foo" would be [0x06, 0x66, 0x6f, 0x6f].

**Comment by chmac** [comment]
@lynixliu That link doesn't work, maybe you can edit your comment to fix it. I copied and pasted it and I see the question.

I created a struct that matches the schema. So my struct looked something like this (sorry, I think this is not valid swift code, I'm typing in GitHub and my editor is not running, but hopefully you get the idea):

```
struct Rec {
  fel: Fel
  struct Fel {
    bea: String
  }
}
```

I was expecting that avro would work like JSON. But maybe you are building the package so that it can on its own decide what the format of the data is, and then give me a variable that matches it? I can see that would be difficult in swift, it seems like it really doesn't handle dynamic types well. In our case I'd be happy to decode it with a known schema (because I converted my avro schema to swift structs) and then just lose any fields which are new in the schema and not in my structs. Just like I believe it works in JSON.

**Comment by lynixliu** [comment]
added a new unit test testNestedRecord() in AvroDecodableTest.swift in pull request https://github.com/lynixliu/SwiftAvroCore/pull/30
Testing schema in JSON:
```
{
    "name": "Rec",
    "type": "record",
    "fields": [
        {
            "name": "fel",
            "type": {
                "name": "Fel",
                "type": "record",
                "fields": [
                    {
                        "name": "bea",
                        "type": "string"
                    },
                    {
                        "name": "Weblogic",
                        "type": "string"
                    }
                ]
            }
        }
    ]
}
```
And Swift structure without field Weblogic:
```
struct Rec: Decodable {
            var fel: Fel
            struct Fel: Decodable {
                var bea: String
            }
}
```

Avro encoded data : [0x06, 0x66, 0x6f, 0x6f] 
Got result of Rec variabal model: model.fel.bea = "foo" 

So the decode test pass. Please verify it from the develop branch, if no other problems,  can I close this issue?

**Comment by chmac** [comment]
That's awesome, thanks a lot @lynixliu. Unfortunately as we're not using avro in Swift any more, I can't easily test this. But I'm happy to close the issue. I really appreciate the effort you made to fix this issue.
