### ISSUE TITLE
Initial error in swift 5

### ISSUE THREAD

**Issue by glve1027** [lynixliu/SwiftAvroCore#3]
Demo 没法正常运行

**Comment by glve1027** [comment]
```swift
let jsonSchema = """
{"type":"record",
"name": "Person",
"namespace": "com.movile.objectiveavro.unittest.v1",
"fields":[
{"name": "requestName", "type": "string"},
]}
"""
let avro = Avro()
guard let schema = avro.decodeSchema(schema: jsonSchema) else {
    return
}
```

这样就直接crash

**Comment by lynixliu** [comment]
Sorry for reply so late, and thanks for your reporting, I am currently busing working on other project, but I will fix this issue in my asap and let you know the progress.

**Comment by lynixliu** [comment]
This issue is fixed, add the demo in Readme in unit test, all unit test cases passed.
