### ISSUE TITLE
Error uploading to App Store

### ISSUE THREAD

**Issue by chmac** [lynixliu/SwiftAvroCore#31]
I accidentally had a copy of this package still inside our app when I tried to upload to the app store and I got this error:

```
ITMS-90535: Unexpected CFBundleExecutable Key - The bundle at '/Payload/xxx.app/SwiftAvroCore/.build/checkouts/Runtime/Tests/RuntimeTests/Info.plist' does not contain a bundle executable. If this bundle intentionally does not contain an executable, consider removing the CFBundleExecutable key from its Info.plist and using a CFBundlePackageType of BNDL. If this bundle is part of a third-party framework, consider contacting the developer of the framework for an update to address this issue.
```

At some point I had dragged the package into the project to be able to edit it and reload in real time. Maybe that was the source of the issue, in which case please feel free to close this issue without comment. I only posted it in case it's helpful in some way. I don't know enough about Swift to know what the issue means.

**Comment by lynixliu** [comment]
Sorry for reply this late, I just come back from a two weeks trip, thanks your feedback, the runtime package is a new introduced package, I will have some build test to find if there have some dependency problems.

**Comment by lynixliu** [comment]
remove the local build directories

**Comment by chmac** [comment]
No worries, I appreciate all the support you gave us with this package. 🧡
