### ISSUE TITLE
A memory leak occurs when writing a file.

### ISSUE THREAD

**Issue by lgbin44** [lynixliu/SwiftAvroCore#34]
public func writeData(url: URL, data: SrcrecJSON) {
        // file write
        do {
            let codec = NullCodec(codecName: AvroReservedConstants.NullCodec)
            var writeObjectContainer = try ObjectContainer(schema: avroSchema, codec: codec)
            try writeObjectContainer.addObject(data)
            let encodeData = try writeObjectContainer.encodeObject()
            try encodeData.write(to: url)
        } catch {
            print("Error writing file: \(error)")
        }
    }

I am encoding json data into avro file and saving it as a file.

The file is encoded properly through the code and saved well.

However, a memory leak occurs every time this operation is performed.
It has been discovered that memory is not organized and continues to accumulate, eventually causing the app to close.

When tracking down memory issues, a problem is suspected with AvroBinaryEncoder.

can you help me?

**Comment by lynixliu** [comment]
Hi,Thanks for your reporting, I am looking at it. I will try my best to fix it in a week.Best regards YangSent from my iPhoneOn 1/11/2023, at 3:40 PM, 임국빈 ***@***.***> wrote:﻿
public func writeData(url: URL, data: SrcrecJSON) {
// file write
do {
let codec = NullCodec(codecName: AvroReservedConstants.NullCodec)
var writeObjectContainer = try ObjectContainer(schema: avroSchema, codec: codec)
try writeObjectContainer.addObject(data)
let encodeData = try writeObjectContainer.encodeObject()
try encodeData.write(to: url)
} catch {
print("Error writing file: (error)")
}
}
I am encoding json data into avro file and saving it as a file.
The file is encoded properly through the code and saved well.
However, a memory leak occurs every time this operation is performed.
It has been discovered that memory is not organized and continues to accumulate, eventually causing the app to close.
When tracking down memory issues, a problem is suspected with AvroBinaryEncoder.
can you help me?

**Comment by lgbin44** [comment]
hello
I found the problematic part.
The problem was solved by modifying the unkeyedContainer function in the AvroBinaryEncoder class.

```
func unkeyedContainer() -> UnkeyedEncodingContainer {
        return AvroUnkeyedEncodingContainer(encoder: self, schema: schema)
 }
```
thank you for the quick reply
have a good day

**Comment by lynixliu** [comment]
Hi @lgbin44 ,
Could you please share me the testing schema in json and the your testing struct? That would be vey helpful to reproduce the problem and fix it.

Thanks
Yang

**Comment by lynixliu** [comment]
I just found your quick fix, that's great!  it seems the unkeyedContainerCache in AvroBinaryEncoder class is not needed any more.  I will remove the cache in the next release.
