### ISSUE TITLE
How to deal with schemas where a value can be nullable 

### ISSUE THREAD

**Issue by jindrichgorner** [lynixliu/SwiftAvroCore#36]
I am struggling to figure out how to deal with a situation when a schema type allows a nullable value. For example: 

` {"name": "fieldName", "type": ["null", "double"]...}`

In Swift if I have a data type set as: 
`
struct Data { 
fieldName: Double? 
}
`

If I try to encode it and send it to our server I am getting the following error: 

`Index 43 out of bounds for length 2`

Similarly, when I try to decode the encoded data through your package I am getting the same error:

`indexOutofBoundary index of union: 43`

Any advice how to go about this issue? 

Thanks!

**Comment by lynixliu** [comment]
Thanks for your issue report. According to the error message, the boundary is decoded correctly, while the item index is wrong, I guest that 43 is the index of the item named 'fieldName' in a union. It would be very helpful if you could provide the parent level of the schema and the swift struct. I am now investing this issue, I will update my progress later.

**Comment by jindrichgorner** [comment]
> Thanks for your issue report. According to the error message, the boundary is decoded correctly, while the item index is wrong, I guest that 43 is the index of the item named 'fieldName' in a union. It would be very helpful if you could provide the parent level of the schema and the swift struct. I am now investing this issue, I will update my progress later.

Many thanks for a quick reply. 

The schema is as follows: 

`"{\"type\":\"record\",\"name\":\"SensorKitTelephonySpeechMetrics\",\"namespace\":\"org.radarcns.passive.apple.sensorkit\",\"doc\":\"Describes the metrics about a range of speech.\",\"fields\":[{\"name\":\"time\",\"type\":\"double\",\"doc\":\"Device timestamp in UTC (s).\"},{\"name\":\"timeReceived\",\"type\":\"double\",\"doc\":\"Device receiver timestamp in UTC (s).\"},{\"name\":\"device\",\"type\":\"string\",\"doc\":\"Device model.\"},{\"name\":\"audioLevelStart\",\"type\":[\"null\",\"double\"],\"doc\":\"The start time of the time range in the audio stream that the level applies to, in seconds relative to time (s).\"},{\"name\":\"audioLevelDuration\",\"type\":[\"null\",\"double\"],\"doc\":\"The duration of the time range in the audio stream that the level applies to (s).\"},{\"name\":\"audioLevelLoudness\",\"type\":[\"null\",\"double\"],\"doc\":\"The measure of the audio level in decibels.\"},{\"name\":\"soundClassificationStart\",\"type\":[\"null\",\"double\"],\"doc\":\"The start time of the time span that corresponds to the result’s classifications, in seconds relative to time (s).\"},{\"name\":\"soundClassificationDuration\",\"type\":[\"null\",\"double\"],\"doc\":\"The duration of the time span that corresponds to the result’s classifications (s).\"},{\"name\":\"soundClassification\",\"type\":[\"null\",\"string\"],\"doc\":\"The confidence value the model has in its prediction.\"},{\"name\":\"speechExpressionStart\",\"type\":[\"null\",\"double\"],\"doc\":\"The start time of the time range in the audio stream that the metrics and analytics apply to, in seconds relative to time (s).\"},{\"name\":\"speechExpressionDuration\",\"type\":[\"null\",\"double\"],\"doc\":\"The duration of the time range in the audio stream that the metrics and analytics apply to (s).\"},{\"name\":\"speechExpressionActivation\",\"type\":[\"null\",\"double\"],\"doc\":\"The level of energy or activation of the speaker.\"},{\"name\":\"speechExpressionConfidence\",\"type\":[\"null\",\"double\"],\"doc\":\"The level of confidence of the speaker.\"},{\"name\":\"speechExpressionDominance\",\"type\":[\"null\",\"double\"],\"doc\":\"The degree of how strong or meek the speaker sounds.\"},{\"name\":\"speechExpressionMood\",\"type\":[\"null\",\"double\"],\"doc\":\"An indication of how slurry, tired, or exhausted the speaker sounds compared to normal speech.\"},{\"name\":\"speechExpressionValence\",\"type\":[\"null\",\"double\"],\"doc\":\"The degree of positive or negative emotion or sentiment of the speaker.\"}]}"`

The struct: 

```
    let time: Double
    let timeReceived: Double
    let device: String
    let audioLevelLoudness: Double?
    let audioLevelStart: Double?
    let audioLevelDuration: Double?
    let speechExpressionStart: Double?
    let speechExpressionDuration: Double?
    let speechExpressionConfidence: Double?
    let speechExpressionMood: Double?
    let speechExpressionValence: Double?
    let speechExpressionActivation: Double?
    let speechExpressionDominance: Double?
    let soundClassificationStart: Double?
    let soundClassificationDuration: Double?
    let soundClassification: String?
```

I did a bit of testing and it seems to me it works fine if unions are changed to Double or if the union is changed to [null, String] 

Many thanks!

**Comment by lynixliu** [comment]
Hi @jindrichgorner ,
I have figured out the problem. This is an encoder error, as the keyed encoder is despatched by the Swift Foundation, which would skip the nil value, and the encoder cannot received the nil attribute of 'fieldName'.  The implementation perviously only append the nil index(in Avro, it is 0x00) for general type(T), while the Swift Foundation clever enough to skip the general type inference, and directly calling the concrete type.
Besides, the decoder is ok, If we add the missing nil index in the input binary, the decoder can decode it to a Swift variable correctly. 
The fix is to check and encode the nil index after encoded each concrete type. I will have some test tomorrow , if there is no other issues, I will release a build version in this week.

**Comment by jindrichgorner** [comment]
Hi @lynixliu,

I had a play around with it before your answer and noticed one thing. Does the order of the fields in the struct matters or not? 

Example: 

```
  {"type":"record",
  "fields":[
  {"name": "doubleField", "type": "double"},
  {"name": "stringFieldOpt", "type":  [\"null\",\"string\"]},
  {"name": "doubleFieldOpt3", "type": [\"null\",\"double\"]},
  {"name": "doubleFieldOpt1", "type": [\"null\",\"double\"]},
  {"name": "doubleFieldOpt2", "type": [\"null\",\"double\"]},
  ]}
```

Encoding and decoding the below code  works fine .
```
  var stringFieldOpt: String?
  var doubleFieldOpt1: Double?
  var doubleFieldOpt2: Double?
  var doubleFieldOpt3: Double?
  var doubleField: Double

TestStr( stringFieldOpt: "Hello", doubleFieldOpt1: 88.0, doubleFieldOpt2: 99.0, doubleFieldOpt3: 33.0, doubleField: 22.0)
```



But if I move  **stringField** in the struct to a different position, it starts erroring with indexOutofBoundary

```
  var doubleFieldOpt1: Double?
  var doubleFieldOpt2: Double?
  var doubleFieldOpt3: Double?
  var doubleField: Double
  var stringFieldOpt: String?

TestStr( doubleFieldOpt1: 88.0, doubleFieldOpt2: 99.0, doubleFieldOpt3: 33.0, doubleField: 22.0, stringFieldOpt: "Hello")
```

This might be related to your description of the problem and might be side effect of that? But I thought I would share it anyway in case there is some other issue ( or I am doing something wrong )  

Thanks a lot for your help on this!

**Comment by lynixliu** [comment]
Thank you so much for your analysis. I am very appreciate it. As the encoding of fields in a structure are dispatched from the swift Foundation, so the AVRO encoder cannot receive the option field encoding call if its value is nil. What we can do is to add some clues when the keyed encoder is initialised, and using this clues after each field was encoded. The previous implement only add this checking in the general type, not all types. So sometimes it works, sometimes not, all related which type of encoding is call from the Foundation. But according to your analysis, I will checking the process of encoding optional strings why it is related to the order. 
By the way, yesterday I already committed the fix to the develop branch, you can try it fixed this bugs. I will have more thoroughly tests according to your analysis before merging this changes to the master branch.

**Comment by lynixliu** [comment]
After some debug, I found that the index error of order in struct related to 'the clues' of each filed. The clue's order should match with the encoding data struct instead of the record schema field order, I am going to update the algorithm to tag the nil field in record struct.

**Comment by jindrichgorner** [comment]
Hi @lynixliu,

I have been testing the data today with the "develop" branch and it is looking good! as long as I keep correct order of fields the data uploads and the server processes it fine. Thank you so much for this quick fix! 

I will do a bit more testing so I will let you know if it still fails somewhere but I don't expect.

**Comment by lynixliu** [comment]
code merged, close this issue as done.
