### ISSUE TITLE
how to decode a Schema only available at runtime?

### ISSUE THREAD

**Issue by wowo4k** [lynixliu/SwiftAvroCore#9]
Hi

I am trying the use your library to decode an Avro message which a get via an API call. From this call, I get two things 1st the Schema for the Message in AVRO, 2nd the AVRO binary data. My challenge is that the Schema is unknown to me upfront and now I am struggling with how I can use the Library to decode my message into something unknown at design time. Do you have any suggestions if this can be done with your library??

Thanks, Armin

**Comment by lynixliu** [comment]
Hi Armin,
Thank you for using this library. Your questions are very appreciated. 

As per the Avro Spec, the schema in a Message should be encoded in the JSON format, which can be decoded directly by this Library: schema = try? Avro().decodeSchema(schema: jsonString)
so you can check the schema type in three ways: 

- The schema is a enum type, you can use "switch case" to check it.
` switch decodedSchema! {
case .recordSchema:
....
 break
}` 
- There are several isNull(), IsInt()... public methods to detect the type (please refer to      SwiftAvroCore/Sources/Schema/AvroSchema+Equatable.swift).
- Get the schema by name by: schema.getName(). (I have just changed it to public today.)

Currently, I am working on porting the IPC features which are not related to specific platforms from my project SwiftAvroRPC to SwiftAvroCore(in develop branch) including:

-  Avro File Object container
-  Avro Protocol Message request/response. 

So users can decode the message directly to a Local type which is defined according to the Protocol. Please stay tuned for the progress of the Develop branch of this Project. 

Please let me know if you have any further questions or requirements. The project also welcomes contributions, if you have any improvement please submit pull requests to make the library better and better. Thanks

**Comment by wowo4k** [comment]
Hi Yang

Many thanks for your reply. Maybe I was not able to clearly express where my problem is. It is not with Schema. It is with decoding of the AVRO data as I can"t define a struct at design time. attached some code to explain my problem better.


 // get JSON Schema for Apache Pulsar Topic
        
        guard let jsonSchema: String = self.getSchema4ApachePulsarTopic()  else {
            return
        }
        
        // function returns:
        //        {
        //          "name" : "NeuronDemoCustomer",
        //          "type" : "record",
        //          "fields" : [
        //            {
        //              "name" : "customerId",
        //              "type" : "string"
        //            },
        //            {
        //              "name" : "firstName",
        //              "type" : "string"
        //            },
        //            {
        //              "name" : "lastName",
        //              "type" : "string"
        //            }
        //          ]
        //        }

        
        guard let schema = avro.decodeSchema (schema: jsonSchema) else {
            return
        }
        
        guard let data: Data = self.getAvroMessage4ApachePulsarTopic() else {
            return
        }
        
        // decode from avro binary
        // and here begins my problem. In principle the Schema is unknown to me,
        // I only get it via the API call and now I have no idea how to decode the AVRO message
        // I can"t define Model struct and did not find a way to do dynamic decoding.
        
        let decodedValue: CantDefineStruct = try! avro.decodeFrom(from: data, schema: schema)

        print(decodedValue)`
```

**Comment by lynixliu** [comment]
Hi Armin,

Thanks your explanation,  your problem is to dynamic decode the unknown type. 
Currently, the library do not provide this feature, as in most time, the receiving type is depend on the communication protocol. But it is a cleaver idea to provide a suggestion type base on the schema.

There are some challenges to handle the recursive type such as Record or Union. The final structure cannot be inferenced before all the primitive type of leaves are determined. It also need some reflection feature to construct the structure Dynamically.

I will list a spec later below, please help to review it after I finished the spec. I will add this feature in the next release. I hope t can be available in this week or next week. 

Thanks Armin

**Comment by lynixliu** [comment]
Feature: type inference according to schema

Decode type mapping:
for primitive type:

- null: nil
- boolean:Bool
- int:Int
- long: Int64
- float:Float
- double:Double
- bytes:[uint8]
- string:String
- fixed: [uint8]/[uint32] for Date

for complex type:

- array:primitive type] 
- record: [String: primitive type] // it is in theory should be a structure, but I have dig into the Reflection feature of swift on how to define a struct on the fly. before that, a map is returned.
- enum: String, value in symbols
- map: [String: primitive type]

**Comment by wowo4k** [comment]
Hi Yang

As far as I can judge it sounds very reasonable for me, but please keep in mind I am at the very beginning of my Swift learning journey.  Thanks a lot for your efforts.

**Comment by lynixliu** [comment]
Hi Armin,

I finished the unit test. I am going to test the branch type-inference-decode-according-to-schema until this weekend and then merge it to the develop and master branch. 
Currently, you can checkout this branch for a try. Please let me know if you found some bugs. Thanks.

In this branch, I added to public functions, they can decode the Data input to a generic : 
`public func decode(from: Data) throws -> Any?`
`public func decodeFrom(from: Data, schema: AvroSchema) throws -> Any?`

Usage:
`let decodedValue = try! avro.decodeFrom(from: data, schema: schema)`
`print(decodedValue!)`
`let t = type(of: values!)`
`print(t)`

**Comment by wowo4k** [comment]
Hi Yang

Continued to work decoding my AVRO message and for one of those, I get the following error at runtime.

Swift/ContiguousArrayBuffer.swift:580: Fatal error: Index out of range
2022-03-09 22:02:59.578564+0100 PulsarEX[67140:2346673] Swift/ContiguousArrayBuffer.swift:580: Fatal error: Index out of range

If helpful I also can share the message and the schema definition.

**Comment by lynixliu** [comment]
Thanks for your message ,I am trying to reproduce from my test cases, but It will be very helpful if you could share me the schema and data. If the index is a negative number, there must be some pervious data was not correctly decoded.

**Comment by wowo4k** [comment]
It did not fix my error. I tried to dump the AVRO Data object using the following code:

```
var dataMap = data.map { String(format: "%02x", $0)}.joined()
dump("\(dataMap)")
```
 ```
"021652564f5441544143585858044c550636383714313936392d31312d313614323032312d30342d3131164c6172612d536f706869650c53636877616208434f5250205269656420696d20496e6e6b7265697302084d61672e"

```

The schema is the following
```
{"fields": [{"name": "bic", "type": ["null", "string"]}, {"name": "countryOfBirth", "type": "string"}, {"name": "customerId", "type": "string"}, {"name": "dateOfBirth", "type": "string"}, {"name": "dateOfOpened", "type": "string"}, {"name": "firstName", "type": "string"}, {"name": "lastName", "type": "string"}, {"name": "lineOfBusiness", "type": "string"}, {"name": "placeOfBirth", "type": "string"}, {"name": "title", "type": ["null", "string"]}], "name": "NeuronDemoCustomer", "type": "record"}
 "021652564f5441544143585858044c550636383714313936392d31312d313614323032312d30342d3131164c6172612d536f706869650c53636877616208434f5250205269656420696d20496e6e6b7265697302084d61672e"

```

I hope this helps to reproduce the error. If I should provide the Data object differently, please let me know. 

Thanks a lot for your efforts.

**Comment by lynixliu** [comment]
Hi Armin,
I added your case in the AvroDecodableTest.swift line 518 - 575 func testCompondeUnion(). But do not reproduce your problem.
I formatted the data to:
Data([0x02, 0x16,0x52,0x56,0x4f,0x54,0x41,0x54,0x41,0x43,0x58,0x58,0x58,0x04,0x4c,0x55,0x06,0x36,0x38,0x37,0x14,0x31,0x39,0x36,0x39,0x2d,0x31,0x31,0x2d,0x31,0x36,0x14,0x32,0x30,0x32,0x31,0x2d,0x30,0x34,0x2d,0x31,0x31,0x16,0x4c,0x61,0x72,0x61,0x2d,0x53,0x6f,0x70,0x68,0x69,0x65,0x0c,0x53,0x63,0x68,0x77,0x61,0x62,0x08,0x43,0x4f,0x52,0x50,0x20,0x52,0x69,0x65,0x64,0x20,0x69,0x6d,0x20,0x49,0x6e,0x6e,0x6b,0x72,0x65,0x69,0x73,0x02,0x08,0x4d,0x61,0x67,0x2e])
as the test Schema defines, the data should be decoded as:
["bic": "RVOTATACXXX", 
"countryOfBirth": "LU", 
"customerId": "687", 
"dateOfBirth": "1969-11-16", 
"dateOfOpened": "2021-04-11",
"firstName": "Lara-Sophie", 
"lastName": "Schwab", 
"lineOfBusiness": "CORP", 
"placeOfBirth": "Ried im Innkreis", 
"title": "Mag."]
Currently, the test correctly decode the data to Any value like:
if let value = try? decoder.decode(from: Data(data)) as! [String:Any] {
...checking fields value
}

But I failed to decode the data to Type like:
struct Model:Codable,Equatable {
        var bic:String?
        var countryOfBirth:String
        var customerId:String
        var dateOfBirth:String
        var dateOfOpened:String
        var firstName:String
        var lastName:String
        var lineOfBusiness:String
        var placeOfBirth:String
        var title:String
    }
I am still working on it. But It seems that's not your problem.

**Comment by lynixliu** [comment]
Hi Armin,
I implemented a missing feature defined in  AVRO spec about negative block count of array and map, I tested with your data and schema. Could you please verify if the latest version of this branch fixed the decode error. 
Thanks a lot.

Yang

**Comment by wowo4k** [comment]
Hi Yang

I can decode my AVRO without any problems.  Many thanks for all your efforts.

Armin

**Comment by lynixliu** [comment]
That's great, I will close this issue and merge it to the master branch.

**Comment by lynixliu** [comment]
merged in [pull request](https://github.com/lynixliu/SwiftAvroCore/commit/6fe8c4d84479dafbbd8ee80c6612a22a554c4c0d) https://github.com/lynixliu/SwiftAvroCore/pull/13
